version: '3'
services:
  postgres:
    restart: always
    image: 'postgres:15'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: be-right-db
    volumes:
      - mysql-storage:/.data

  app:
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - '8000:5000'
    env_file:
      - .env

volumes:
  mysql-storage:
