version: '3'
services:
  postgres:
    restart: always
    image: 'postgres:10'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: be-right-db
    volumes:
      - mysql-storage:/.data

  redis:
    image: 'redis:alpine'
    ports: # ext
      - '6379:6379'
    # expose: # interne
    #   - 6379

  app:
    links:
    - redis
    depends_on:
      - redis
      - postgres
    build:
      context: .
      args:
      - SCRIPT: '/app/entrypoint.sh'
    ports:
      - '8080:8080'
    env_file:
      - .env

  cron:
    depends_on:
      - redis
      - postgres
    build:
      context: .
      args:
      - SCRIPT: '/app/cronScript.sh'

      # dockerfile: ./cron.Dockerfile
      # regarder pour lancer le conteneur avec comme Arg le bon arg
    env_file:
      - .env


volumes:
  mysql-storage:
