version: '3'
services:
  postgres:
    restart: always
    image: 'postgres:15'
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: be-right-db
    volumes:
      - mysql-storage:/.data

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    expose:
      - 6379

volumes:
  mysql-storage:
