export enum PaymentStatusEnum {
  PAYMENT_STATUS_CREATED = 'PAYMENT_STATUS_CREATED',
  PAYMENT_STATUS_SUBMITTED = 'PAYMENT_STATUS_SUBMITTED',
  PAYMENT_STATUS_PAID = 'PAYMENT_STATUS_PAID',
  PAYMENT_STATUS_REJECTED = 'PAYMENT_STATUS_REJECTED'
}

export enum CurrencyEnum {
  EUR = 'EUR',
}
